// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkuaevqmfaklooeeypln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrdWFldnFtZmFrbG9vZWV5cGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTUwNjcsImV4cCI6MjA3NDI5MTA2N30.POQpHX3-ek00b4wD-uRw-qPmKeTEpsNjKOU5k3eWe_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});